name: Test on MySQL

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        operating_system: ['ubuntu-20.04']
        mysql_versions:
          - 'mariadb-10.2'
          - 'mariadb-10.3'
          - 'mariadb-10.4'
          - 'mariadb-10.5'
          - 'mariadb-10.6'
          - 'mariadb-10.7'
          - 'mariadb-10.8'
          - 'mariadb-10.9'
          - 'mariadb-10.10'
          - 'mariadb-10.11'
          - 'mariadb-11.0'
          - 'mariadb-11.1'
          - 'mariadb-11.2'
          - '5.6'
          - '5.7'
        include:
          -
            operating_system: 'ubuntu-20.04'
            mysql_versions: 'mariadb-11.3'
          -
            operating_system: 'ubuntu-22.04'
            mysql_versions: '8.0'
          -
            operating_system: 'ubuntu-22.04'
            mysql_versions: '8.1'
          -
            operating_system: 'ubuntu-22.04'
            mysql_versions: 'mariadb-11.4'
          -
            operating_system: 'ubuntu-22.04'
            mysql_versions: 'mariadb-11.5'
          -
            operating_system: 'ubuntu-22.04'
            mysql_versions: 'mariadb-11.6'
          -
            operating_system: 'ubuntu-24.04'
            mysql_versions: '8.2'
          -
            operating_system: 'ubuntu-24.04'
            mysql_versions: '8.3'
          -
            operating_system: 'ubuntu-24.04'
            mysql_versions: '8.4'
          -
            operating_system: 'ubuntu-24.04'
            mysql_versions: '9.0'

    runs-on: '${{ matrix.operating_system }}'

    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: ${{ matrix.mysql_versions }}
      - run: mysql -v -v -v -e 'SELECT version();' -uroot
